// GENERATED by a one-off script (fn-1 task .2 spike): ~50-service synthetic graph for the
// type-level captive-dependency check cost measurement. Checked by `tsc --noEmit`.
import { Context, Effect } from 'effect'
import { expectTypeOf } from 'vitest'
import { service, type CaptiveViolations } from '../service'

class T0 extends Context.Tag('T0')<T0, { n: 0 }>() {}
class T1 extends Context.Tag('T1')<T1, { n: 1 }>() {}
class T2 extends Context.Tag('T2')<T2, { n: 2 }>() {}
class T3 extends Context.Tag('T3')<T3, { n: 3 }>() {}
class T4 extends Context.Tag('T4')<T4, { n: 4 }>() {}
class T5 extends Context.Tag('T5')<T5, { n: 5 }>() {}
class T6 extends Context.Tag('T6')<T6, { n: 6 }>() {}
class T7 extends Context.Tag('T7')<T7, { n: 7 }>() {}
class T8 extends Context.Tag('T8')<T8, { n: 8 }>() {}
class T9 extends Context.Tag('T9')<T9, { n: 9 }>() {}
class T10 extends Context.Tag('T10')<T10, { n: 10 }>() {}
class T11 extends Context.Tag('T11')<T11, { n: 11 }>() {}
class T12 extends Context.Tag('T12')<T12, { n: 12 }>() {}
class T13 extends Context.Tag('T13')<T13, { n: 13 }>() {}
class T14 extends Context.Tag('T14')<T14, { n: 14 }>() {}
class T15 extends Context.Tag('T15')<T15, { n: 15 }>() {}
class T16 extends Context.Tag('T16')<T16, { n: 16 }>() {}
class T17 extends Context.Tag('T17')<T17, { n: 17 }>() {}
class T18 extends Context.Tag('T18')<T18, { n: 18 }>() {}
class T19 extends Context.Tag('T19')<T19, { n: 19 }>() {}
class T20 extends Context.Tag('T20')<T20, { n: 20 }>() {}
class T21 extends Context.Tag('T21')<T21, { n: 21 }>() {}
class T22 extends Context.Tag('T22')<T22, { n: 22 }>() {}
class T23 extends Context.Tag('T23')<T23, { n: 23 }>() {}
class T24 extends Context.Tag('T24')<T24, { n: 24 }>() {}
class T25 extends Context.Tag('T25')<T25, { n: 25 }>() {}
class T26 extends Context.Tag('T26')<T26, { n: 26 }>() {}
class T27 extends Context.Tag('T27')<T27, { n: 27 }>() {}
class T28 extends Context.Tag('T28')<T28, { n: 28 }>() {}
class T29 extends Context.Tag('T29')<T29, { n: 29 }>() {}
class T30 extends Context.Tag('T30')<T30, { n: 30 }>() {}
class T31 extends Context.Tag('T31')<T31, { n: 31 }>() {}
class T32 extends Context.Tag('T32')<T32, { n: 32 }>() {}
class T33 extends Context.Tag('T33')<T33, { n: 33 }>() {}
class T34 extends Context.Tag('T34')<T34, { n: 34 }>() {}
class T35 extends Context.Tag('T35')<T35, { n: 35 }>() {}
class T36 extends Context.Tag('T36')<T36, { n: 36 }>() {}
class T37 extends Context.Tag('T37')<T37, { n: 37 }>() {}
class T38 extends Context.Tag('T38')<T38, { n: 38 }>() {}
class T39 extends Context.Tag('T39')<T39, { n: 39 }>() {}
class T40 extends Context.Tag('T40')<T40, { n: 40 }>() {}
class T41 extends Context.Tag('T41')<T41, { n: 41 }>() {}
class T42 extends Context.Tag('T42')<T42, { n: 42 }>() {}
class T43 extends Context.Tag('T43')<T43, { n: 43 }>() {}
class T44 extends Context.Tag('T44')<T44, { n: 44 }>() {}
class T45 extends Context.Tag('T45')<T45, { n: 45 }>() {}
class T46 extends Context.Tag('T46')<T46, { n: 46 }>() {}
class T47 extends Context.Tag('T47')<T47, { n: 47 }>() {}
class T48 extends Context.Tag('T48')<T48, { n: 48 }>() {}
class T49 extends Context.Tag('T49')<T49, { n: 49 }>() {}

const D0 = service(T0, { requires: [], lifetime: 'app' }, () => Effect.succeed({ n: 0 as const }))
const D1 = service(T1, { requires: [T0], lifetime: 'app' }, () => Effect.succeed({ n: 1 as const }))
const D2 = service(T2, { requires: [T1, T0], lifetime: 'app' }, () => Effect.succeed({ n: 2 as const }))
const D3 = service(T3, { requires: [T2, T1], lifetime: 'app' }, () => Effect.succeed({ n: 3 as const }))
const D4 = service(T4, { requires: [T3, T2], lifetime: 'app' }, () => Effect.succeed({ n: 4 as const }))
const D5 = service(T5, { requires: [T4, T3], lifetime: 'app' }, () => Effect.succeed({ n: 5 as const }))
const D6 = service(T6, { requires: [T5, T4], lifetime: 'app' }, () => Effect.succeed({ n: 6 as const }))
const D7 = service(T7, { requires: [T6, T5], lifetime: 'app' }, () => Effect.succeed({ n: 7 as const }))
const D8 = service(T8, { requires: [T7, T6], lifetime: 'app' }, () => Effect.succeed({ n: 8 as const }))
const D9 = service(T9, { requires: [T8, T7], lifetime: 'app' }, () => Effect.succeed({ n: 9 as const }))
const D10 = service(T10, { requires: [T9, T8], lifetime: 'app' }, () => Effect.succeed({ n: 10 as const }))
const D11 = service(T11, { requires: [T10, T9], lifetime: 'app' }, () => Effect.succeed({ n: 11 as const }))
const D12 = service(T12, { requires: [T11, T10], lifetime: 'app' }, () => Effect.succeed({ n: 12 as const }))
const D13 = service(T13, { requires: [T12, T11], lifetime: 'app' }, () => Effect.succeed({ n: 13 as const }))
const D14 = service(T14, { requires: [T13, T12], lifetime: 'app' }, () => Effect.succeed({ n: 14 as const }))
const D15 = service(T15, { requires: [T14, T13], lifetime: 'app' }, () => Effect.succeed({ n: 15 as const }))
const D16 = service(T16, { requires: [T15, T14], lifetime: 'app' }, () => Effect.succeed({ n: 16 as const }))
const D17 = service(T17, { requires: [T16, T15], lifetime: 'app' }, () => Effect.succeed({ n: 17 as const }))
const D18 = service(T18, { requires: [T17, T16], lifetime: 'app' }, () => Effect.succeed({ n: 18 as const }))
const D19 = service(T19, { requires: [T18, T17], lifetime: 'app' }, () => Effect.succeed({ n: 19 as const }))
const D20 = service(T20, { requires: [T19, T0], lifetime: 'request' }, () => Effect.succeed({ n: 20 as const }))
const D21 = service(T21, { requires: [T20, T1], lifetime: 'request' }, () => Effect.succeed({ n: 21 as const }))
const D22 = service(T22, { requires: [T21, T2], lifetime: 'request' }, () => Effect.succeed({ n: 22 as const }))
const D23 = service(T23, { requires: [T22, T3], lifetime: 'request' }, () => Effect.succeed({ n: 23 as const }))
const D24 = service(T24, { requires: [T23, T4], lifetime: 'request' }, () => Effect.succeed({ n: 24 as const }))
const D25 = service(T25, { requires: [T24, T5], lifetime: 'request' }, () => Effect.succeed({ n: 25 as const }))
const D26 = service(T26, { requires: [T25, T6], lifetime: 'request' }, () => Effect.succeed({ n: 26 as const }))
const D27 = service(T27, { requires: [T26, T7], lifetime: 'request' }, () => Effect.succeed({ n: 27 as const }))
const D28 = service(T28, { requires: [T27, T8], lifetime: 'request' }, () => Effect.succeed({ n: 28 as const }))
const D29 = service(T29, { requires: [T28, T9], lifetime: 'request' }, () => Effect.succeed({ n: 29 as const }))
const D30 = service(T30, { requires: [T29, T10], lifetime: 'request' }, () => Effect.succeed({ n: 30 as const }))
const D31 = service(T31, { requires: [T30, T11], lifetime: 'request' }, () => Effect.succeed({ n: 31 as const }))
const D32 = service(T32, { requires: [T31, T12], lifetime: 'request' }, () => Effect.succeed({ n: 32 as const }))
const D33 = service(T33, { requires: [T32, T13], lifetime: 'request' }, () => Effect.succeed({ n: 33 as const }))
const D34 = service(T34, { requires: [T33, T14], lifetime: 'request' }, () => Effect.succeed({ n: 34 as const }))
const D35 = service(T35, { requires: [T0, T15], lifetime: 'component' }, () => Effect.succeed({ n: 35 as const }))
const D36 = service(T36, { requires: [T35, T16], lifetime: 'component' }, () => Effect.succeed({ n: 36 as const }))
const D37 = service(T37, { requires: [T36, T17], lifetime: 'component' }, () => Effect.succeed({ n: 37 as const }))
const D38 = service(T38, { requires: [T37, T18], lifetime: 'component' }, () => Effect.succeed({ n: 38 as const }))
const D39 = service(T39, { requires: [T38, T19], lifetime: 'component' }, () => Effect.succeed({ n: 39 as const }))
const D40 = service(T40, { requires: [T39, T0], lifetime: 'component' }, () => Effect.succeed({ n: 40 as const }))
const D41 = service(T41, { requires: [T40, T1], lifetime: 'component' }, () => Effect.succeed({ n: 41 as const }))
const D42 = service(T42, { requires: [T41, T2], lifetime: 'component' }, () => Effect.succeed({ n: 42 as const }))
const D43 = service(T43, { requires: [T42, T3], lifetime: 'component' }, () => Effect.succeed({ n: 43 as const }))
const D44 = service(T44, { requires: [T43, T4], lifetime: 'component' }, () => Effect.succeed({ n: 44 as const }))
const D45 = service(T45, { requires: [T44, T5], lifetime: 'component' }, () => Effect.succeed({ n: 45 as const }))
const D46 = service(T46, { requires: [T45, T6], lifetime: 'component' }, () => Effect.succeed({ n: 46 as const }))
const D47 = service(T47, { requires: [T46, T7], lifetime: 'component' }, () => Effect.succeed({ n: 47 as const }))
const D48 = service(T48, { requires: [T47, T8], lifetime: 'component' }, () => Effect.succeed({ n: 48 as const }))
const D49 = service(T49, { requires: [T48, T9], lifetime: 'component' }, () => Effect.succeed({ n: 49 as const }))

const graph = [D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19, D20, D21, D22, D23, D24, D25, D26, D27, D28, D29, D30, D31, D32, D33, D34, D35, D36, D37, D38, D39, D40, D41, D42, D43, D44, D45, D46, D47, D48, D49] as const
expectTypeOf<CaptiveViolations<typeof graph>>().toEqualTypeOf<never>()

// component <- request is always rejected
const Bad = service(T49, { requires: [T34], lifetime: 'component' }, () => Effect.succeed({ n: 49 as const }))
const badGraph = [...graph, Bad] as const
expectTypeOf<CaptiveViolations<typeof badGraph>>().toEqualTypeOf<'T49 (component) captures T34 (request)'>()
