/**
 * apps/showcase/src/__tests__/graph.test.ts
 *
 * /graph lists every analyzer root with its kind: the app root, RequestLive and DemoLive. An unknown
 * kind renders as a plain root.
 */
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { afterEach, describe, expect, it, vi } from 'vitest'
import * as report from '../delivery/report.server'
import GraphPage from '../../app/graph/page'

afterEach(() => vi.restoreAllMocks())

describe('/graph', () => {
  it('lists RequestLive and DemoLive with their kind, after the app root', () => {
    // The roots `sleekstack check` emits for the showcase (packages/cli check.test.ts pins that side);
    // `.sleekstack/` is generated by the build, so it is not read here.
    const root = (name: string, kind: string) => ({ root: name, kind, graph: { root: name, nodes: [], edges: [] }, errors: [] })
    vi.spyOn(report, 'readReport').mockReturnValue({
      ok: true,
      roots: [root('src/delivery/runtime.server.ts:23', 'app'), root('RequestLive', 'request'), root('DemoLive', 'overrides')],
    })
    const html = renderToStaticMarkup(createElement(GraphPage))
    const app = html.indexOf('[app]')
    expect(app).toBeGreaterThan(-1)
    expect(html.indexOf('RequestLive [request]')).toBeGreaterThan(app)
    expect(html.indexOf('DemoLive [overrides]')).toBeGreaterThan(app)
  })

  it('renders an unknown kind as a plain root', () => {
    const graph = { root: 'Later', nodes: [], edges: [] }
    vi.spyOn(report, 'readReport').mockReturnValue({ ok: true, roots: [{ root: 'Later', kind: 'future', graph, errors: [] }] })
    const html = renderToStaticMarkup(createElement(GraphPage))
    expect(html).toContain('<h2>Later</h2>')
  })
})
